### ISSUE TITLE
Front-end isn't running in IE11 & Edge

### ISSUE THREAD

**Issue by bkehren** [Kentico/KInspector#42] opened 2015-09-08 19:25 UTC
By default when I execute the .cmd file, it is opening IE.  I'm running IE11 version 11.0.9600.17937 on Windows 8.1 Pro.  When I execute the .cmd file, it is displaying an error for scripts and doesn't allow me to select AD or SQL server authentication.  When I run it in Chrome or FF it runs without issue.

**Comment by petrsvihlik** [comment] 2015-09-09 13:46
The problem is that window.localStorage is unavailable in IE when using file://url.
We have to consider hosting the front end in IISExpress or selfhosting via OWIN (where the WebAPI is already hosted).

    .\KInspector\KInspector.Web\Program.cs

**Comment by bkehren** [comment] 2015-09-09 19:19
I was assuming it was something like that.  Could you set the launching of a browser be the operating systems default browser vs. IE?  I've set mine to be Chrome and I know many other devs don't have IE as their default.

**Comment by petrsvihlik** [comment] 2015-09-09 19:30
I'm pretty certain that it launches system's default...'cause it calls `Process.Start(".\\FrontEnd\\index.html");`
In my case it runs Chrome. Check what's your default program for opening `.html` files. (`.html != url shortcut`). I guess it'll be IE.

**Comment by ondrejsevcik** [comment] 2015-09-22 07:17
Fixed in #43

**Closed by ondrejsevcik** 2015-09-22 07:17 UTC
Labels: bug
