### ISSUE TITLE
Suggestion: Check for the usage of the {%CurrentDocument%} macro

### ISSUE THREAD

**Issue by jokob** [Kentico/KInspector#85] opened 2016-03-04 04:26 UTC
CurrentDocument may be usually rewrittent to CurrentPageInfo for performance improvemnts

**Comment by ondrejsevcik** [comment] 2016-03-07 08:44
It's a duplicate of #6. We just need to improve description of it :)

**Closed by ondrejsevcik** 2016-03-07 08:44 UTC
