### ISSUE TITLE
Content tree consistency analysis report fails when there are pages using a folder page type

### ISSUE THREAD

**Issue by yuriys-kentico** [Kentico/KInspector#324] opened 2019-12-06 15:56 UTC
### Brief bug description

Content tree consistency analysis report fails when there are pages using a folder page type, which has no table.

### Repro steps

1. Use an instance with pages using a page type that is a folder
2. Run the report

### Expected behavior

Report produces a result

**Comment by kentico-ericd** [comment] 2023-08-03 21:45
Closing- can't reproduce on Dancing Goat sample site

**Closed by kentico-ericd** 2023-08-03 21:45 UTC
