### ISSUE TITLE
Password policy settings incorrect recommendation

### ISSUE THREAD

**Issue by kentico-ericd** [Kentico/KInspector#171] opened 2018-03-26 16:33 UTC
The Password policy settings module will flag CMSPasswordFormat when set to PBKDF2. It claims _"The CMSPasswordFormat should be set to 'SHA2SALT'"_ but our documentation states that PBKDF2 is the most secure option: https://docs.kentico.com/k10/securing-websites/designing-secure-websites/securing-user-accounts-and-passwords/setting-the-user-password-format

**Comment by ChristopherJennings** [comment] 2018-09-24 21:13
Duplicate of #161, whic hwas fixed in PR #168, and released in version 3.8

**Closed by ChristopherJennings** 2018-09-24 21:13 UTC
Labels: bug, good first issue, hacktoberfest, help wanted, up-for-grabs
